- name: install supervisor
  apt: name=supervisor state=installed
- name: configure supervisor
  template: src=supervisord.conf.j2 dest=/etc/supervisor/supervisord.conf
  notify:
    - enable supervisor
